# Generated by Django 6.0.3 on 2026-07-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(default='student@example.com', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(default='Computer Science', max_length=50)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('gpa', models.FloatField()),
                ('enrollment_Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
